name: Create Modpack Package

# This section defines when the workflow will run
on:
  # This allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      # Check out your repository code so we can access its files
      - name: Checkout repository
        uses: actions/checkout@v4

      # Read name and version from manifest.json to name the final zip file
      - name: Read package info from manifest.json
        run: |
          MOD_NAME=$(jq -r '.name' manifest.json)
          MOD_VERSION=$(jq -r '.version' manifest.json)

          echo "MOD_NAME=${MOD_NAME}" >> $GITHUB_ENV
          echo "MOD_VERSION=${MOD_VERSION}" >> $GITHUB_ENV

      # Upload the specific files and folders as a zipped artifact
      - name: Create and Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          # This name becomes the final .zip filename (e.g., Damned-Halls-0.1.0.zip)
          name: ${{ replace(env.MOD_NAME, ' ', '-') }}-${{ env.MOD_VERSION }}
          
          path: |
            overrides/
            modlist.html
            manifest.json
