name: Create Modpack Package

# This section defines when the workflow will run
on:
  # This allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-package:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Check out your repository code so we can access its files
      - name: Checkout repository
        uses: actions/checkout@v4

      #  Read info from manifest.json and prepare the final artifact name
      - name: Prepare Variables
        id: prep
        run: |
          MOD_NAME=$(jq -r '.name' manifest.json)
          MOD_VERSION=$(jq -r '.version' manifest.json)
          
          SANITIZED_NAME=$(echo "$MOD_NAME" | tr ' ' '-')
          
          ARTIFACT_NAME="${SANITIZED_NAME}-${MOD_VERSION}"
          
          echo "Final artifact name will be: $ARTIFACT_NAME"
          
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> "$GITHUB_ENV"

      - name: Create and Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          
          path: |
            overrides/
            modlist.html
            manifest.json
